# Generated by Django 2.2.1 on 2019-06-04 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190430_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='service',
        ),
        migrations.AddField(
            model_name='alert',
            name='service_unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
