# Generated by Django 2.2.2 on 2019-06-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='sms',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='wechat',
            field=models.TextField(default=''),
        ),
    ]
