# Generated by Django 2.2.2 on 2019-06-17 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190612_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='channels',
        ),
    ]
