# Generated by Django 2.2.2 on 2019-06-17 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_alert_channels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='service_unique_id',
            new_name='unique_id',
        ),
    ]
