# Generated by Django 2.2.2 on 2019-06-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190618_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='service_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='last_alert_timestamp',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='last_check_timestamp',
            field=models.CharField(default='', max_length=200),
        ),
    ]
